export const SPEAKERS = [
  {
    // 맨앞에 더미데이터 입니다.
    title: "Speakers",
    sub1: "총 4개의 트랙에서 펼쳐질",
    sub2: "KWDC23의 다양한 세션을 확인해보세요.",
  },
  {
    title: "미국에서 바라본 애플 생태계(feat. WWDC23)",
    category: "Apple eco-system",
    speaker: "Snack ・ 남관식",
    image: "./resources/speaker/snack.png",
    belong: "Apple Developer Academy @ POSTECH",
    introduce: "보다 더 넓은 세상으로 나아가려 합니다.",
    detail: "WWDC23을 참가하기 위해 미국을 다녀오며 직접 보았던 애플 생태계에 대해 공유합니다.",
    track: "1",
    time: "11:00 ~ 11:20",
    linkTitle1: "🔗  LinkedIn",
    link1: "https://www.linkedin.com/in/kwansiknam/",
    linkTitle2: "🔗  Instagram",
    link2: "https://www.instagram.com/namsik._.2/"
  },
  {
    title: "WWDC23 Recap",
    category: "Apple eco-system",
    speaker: "dadahae",
    image: "./resources/speaker/dadahae.png",
    belong: "charming swift",
    introduce: "기록과 정리, 그리고 러닝을 좋아합니다. 물론 개발도요!",
    detail: "WWDC23 세션을 같이 살펴보아요!",
    track: "1",
    time: "11:00 ~ 11:20",
    linkTitle1: "🔗  GitHub",
    link1: "https://github.com/dahae0320",
    linkTitle2: "🔗  Blog",
    link2: "https://dadahae0320.tistory.com/"
  },
  {
    title: "애플이 당신의 건강에 미치는 영향",
    category: "Apple eco-system",
    speaker: "링고",
    image: "./resources/speaker/lingo.png",
    belong: "Apple Developer Academy @ POSTECH",
    introduce: "보다 더 넓은 세상으로 나아가려 합니다.",
    detail: "애플은 HealthKit을 통해 사용자의 건강 데이터를 추적, 관리하고 있어요. 잘 알려지지 않았지만 ResearchKit과 CareKit으로 의료 관련한 데이터를 수집할 수도 있답니다. 애플이 그리는 의료의 미래는 뭘까요?",
    track: "1",
    time: "11:00 ~ 11:20",
    linkTitle1: "🔗  LinkedIn",
    link1: "https://www.linkedin.com/in/seongkwanyoon/",
  },
  {
    title: "ML과 애플의 맛있는 조합, 한 걸음 더 내딛기",
    category: "Apple eco-system",
    speaker: "Jason",
    image: "./resources/speaker/jason_lee.png",
    belong: "Apple Developer Academy @ POSTECH",
    introduce: "애플 개발자 아카데미에서 테크멘토로 근무하고 있습니다.",
    detail: "애플이 ML 기술의 복잡성을 어떻게 단순화하고 발전시켜 활용하고 제공하는지 이야기 합니다!",
    track: "1",
    time: "11:00 ~ 11:20",
    linkTitle1: "🔗  LinkedIn",
    link1: "https://www.linkedin.com/in/json-lee/",
  },
  {
    title: "10년된 서비스의 디자인 시스템 적용기",
    category: "Design",
    speaker: "엽",
    image: "./resources/speaker/엽.png",
    belong: "네이버",
    introduce: "",
    detail: "글로벌 서비스는 디자인 시스템을 어떻게 만들까? 디자인시스템을 만들기 위해 개발자와 디자이너는 어떻게 소통했을까?",
    track: "1",
    time: "11:00 ~ 11:20",
    linkTitle1: "🔗  LinkedIn",
    link1: "https://www.linkedin.com/in/jong-youp-k-197472a3/",
    linkTitle2: "🔗  Instagram",
    link2: "https://instagram.com/todaysyop/"
  },
  {
    title: "iOS17 커뮤니케이션 도구의 변화",
    category: "Business",
    speaker: "Yong",
    image: "./resources/speaker/yong.png",
    belong: "Kakao",
    introduce: "어쩌다 기획자가 된 5년차 서비스 기획자 용이라고 합니다.",
    detail: "iOS17이후 변경된 커뮤니케이션 도구의 변화와 메신저 서비스가 준비해야할 것들",
    track: "1",
    time: "11:00 ~ 11:20",
    linkTitle1: "🔗  Instagram",
    link1: "https://instagram.com/leecy0206/",
  },
  {
    title: "유저스토리를 활용한 프로젝트 진행의 장단점",
    category: "Business",
    speaker: "도그냥",
    image: "./resources/speaker/dognyang.png",
    belong: "카카오스타일",
    introduce: "이커머스를 만드는 일을 13년째 하고 있습니다. 과거에는 서비스기획자로 불렸고 지금은 프로덕트오너로 불리지만 업무만은 프로덕트매니저의 태도를 지향하고 있습니다. 온라인 상에서 도그냥이라는 이름으로 PM/PO/서비스기획자를 위한 글과 영상을 만드는 취미생활을 합니다.",
    detail: "폭포수 프로젝트에 익숙한 팀원들이 크로스펑셔널팀으로 유저스토리 활용 프로젝트 진행시 겪은 좋은 점과 어려운 점들을 공유합니다.",
    track: "1",
    time: "11:00 ~ 11:20",
    linkTitle1: "🔗  Blog",
    link1: "http://brunch.co.kr/@windydog/",
    linkTitle2: "🔗  YouTube",
    link2: "https://www.youtube.com/@towardlee/"
  },
  {
    title: "시장에서 살아나는 제품 만들기",
    category: "Business",
    speaker: "킹홍",
    image: "./resources/speaker/kinghong.png",
    belong: "TheB",
    introduce: "IT를 통해 비즈니스를 성장시킵니다. 안녕하세요. 저는 TheB 라는 스타트업에서 CEO로 일하며 IT프로덕트의 전반적인 제품 기획과 개발을 담당하고 있습니다. 저는 여러 기업에서 ‘개발자 → UX 디자이너 → 프로덕트 매니저 → IR 담당자 → 프로덕트 총괄’의 커리어를 거쳐오며 비즈니스와 제품을 함께 성장시키는 일을 해왔습니다.",
    detail: "투자가 얼어붙은 시장에서 PMF를 찾고, 지표를 성장시키고 살아남는 사례와 경험을 공유하고 싶습니다.",
    track: "1",
    time: "11:00 ~ 11:20",
  },
  {
    title: "현대차 그리고 셔클",
    category: "Sponsorship session",
    speaker: "김용덕",
    image: "./resources/speaker/hyun_kim.png",
    belong: "현대자동차",
    introduce: "",
    detail: "현대자동차에서는 자동차만 만드는 것이 아닌, 모빌리티 서비스도 함께 만들고 있습니다.",
    track: "1",
    time: "11:00 ~ 11:20",
  },
  {
    title: "제조업에서 SwiftUI + TCA로 앱 개발하기",
    category: "Sponsorship session",
    speaker: "강성규",
    image: "./resources/speaker/hyun_kang.png",
    belong: "현대자동차",
    introduce: "",
    detail: "곧 공개됩니다.",
    track: "1",
    time: "11:00 ~ 11:20",
  },
  {
    title: "생성형AI 기반의 에듀테크 플랫폼",
    category: "Sponsorship session",
    speaker: "최삼락 상무",
    image: "./resources/speaker/udemy.png",
    belong: "웅진씽크빅 Udemy",
    introduce: "교육업계 최초의 클라우드 전환. 1위 AI 학습 플랫폼, 웅진스마트올.",
    detail: "웅진스마트올 iOS 서비스 개발 사례 생성형AI를 통한 도약. Udemy를 통한 리스킬링&업스킬링",
    track: "1",
    time: "11:00 ~ 11:20",
  },
  {
    title: "Deep dive to SwiftUI Animation",
    category: "Programming",
    speaker: "그린",
    image: "./resources/speaker/그린.png",
    belong: "한화생명",
    introduce: "불확실성에 도전하는 개발자",
    detail: "SwiftUI Animation이라는 바다를 헤엄쳐 봅시다!",
    track: "1",
    time: "11:00 ~ 11:20",
    linkTitle1: "🔗  GitHub",
    link1: "https://github.com/GREENOVER",
    linkTitle2: "🔗  Blog",
    link2: "https://green1229.tistory.com/"
  },
  {
    title: "Swift 언어 히스토리 탐방",
    category: "Programming",
    speaker: "라이노",
    image: "./resources/speaker/라이노.png",
    belong: "비바리퍼블리카",
    introduce: "코딩의 가능성을 탐구하는 것을 즐깁니다.",
    detail: "Swift 언어가 발전해온 내용들과 올해 추가된 내용들을 리뷰하면서 Swift의 미래에 대한 생각을 나눕니다.",
    track: "1",
    time: "11:00 ~ 11:20",
    linkTitle1: "🔗  GitHub",
    link1: "https://github.com/JCSooHwanCho",
    linkTitle2: "🔗  LinkedIn",
    link2: "https://www.linkedin.com/in/soohwan-cho-60468a19b/"
  },
  {
    title: "Push Notifications Console 여행하기",
    category: "Programming",
    speaker: "아렉스",
    image: "./resources/speaker/아렉스.png",
    belong: "식신(주)",
    introduce: "인생은 trip",
    detail: "새롭게 소개 된 Push Notifications Console을 소개하며, 앞으로 어떻게 활용할지에 대해 얘기하고 싶습니다.",
    track: "1",
    time: "11:00 ~ 11:20",
  },
  {
    title: "LiDAR 스캐너의 활용법: Point Cloud Data, Object Capture",
    category: "Programming",
    speaker: "Tony",
    image: "./resources/speaker/tony.png",
    belong: "",
    introduce: "앱 개발이 취미입니다. 재밌는 아이디어는 못참죠.",
    detail: "LiDAR 스캐너로 Point Cloud Data와 새롭게 소개된 Object Capture 기능으로 3D 오브젝트를 스캔하는 방법들을 소개합니다.",
    track: "1",
    time: "11:00 ~ 11:20",
    linkTitle1: "🔗  GitHub",
    link1: "https://github.com/FreeDeveloper97/",
    linkTitle2: "🔗  YouTube",
    link2: "https://www.instagram.com/dev_fdee/"
  },
  {
    title: "좋은 앱은 무엇일까요? 접근성 지원을 위한 iOS 개발자의 첫걸음",
    category: "Programming",
    speaker: "루카스 ・ 허성진",
    image: "./resources/speaker/lucas.png",
    belong: "인포마이닝",
    introduce: "귀여움받는 유능한 개발자가 되기 위해 열심히 노력하고 있습니다.",
    detail: "애플의 접근성 지원에 대한 진정성과, 개발자가 접근성 지원을 하면 얻는 이점을 이야기해 봅니다.",
    track: "1",
    time: "11:00 ~ 11:20",
    linkTitle1: "🔗  GitHub",
    link1: "https://github.com/heoseongjin/",
  },
  {
    title: "매크로 부수고 부서지기",
    category: "Programming",
    speaker: "naljin",
    image: "./resources/speaker/nal.png",
    belong: "지마켓",
    introduce: "우당탕탕 좌충우돌 얼레벌레 iOS 대모험",
    detail: "매크로에 대한 정의, 도입 이유, 디자인 철학, 동작 원리, 작성 방법 등을 전반적으로 살펴볼 예정입니다.",
    track: "1",
    time: "11:00 ~ 11:20",
    linkTitle1: "🔗  Blog",
    link1: "https://sujinnaljin.medium.com/",
  },
  {
    title: "매크로 부수고 부서지기",
    category: "Programming",
    speaker: "소들이",
    image: "./resources/speaker/소들이.png",
    belong: "아프리카TV",
    introduce: "기록을 좋아하는 개발자입니다.",
    detail: "매크로에 대한 정의, 도입 이유, 디자인 철학, 동작 원리, 작성 방법 등을 전반적으로 살펴볼 예정입니다.",
    track: "1",
    time: "11:00 ~ 11:20",
    linkTitle1: "🔗  Blog",
    link1: "https://babbab2.tistory.com/",
  },
  {
    title: "글로벌 앱을 위한 Localization: 번역은 시작일뿐",
    category: "Programming",
    speaker: "애플사이다",
    image: "./resources/speaker/apple-sider.png",
    belong: "백패커(아이디어스)",
    introduce: "지속 가능한 성장을 지향합니다",
    detail: "새로운 Localization 기능을 알아보고, 글로벌 앱 예시를 통해 기술적 고민과 해결 방법을 소개합니다.",
    track: "1",
    time: "11:00 ~ 11:20",
    linkTitle1: "🔗  Blog",
    link1: "https://applecider2020.tistory.com/",
    linkTitle2: "🔗  Instagram",
    link2: "https://instagram.com/liah_dev/"
  },
  {
    title: "우리가 모듈화를 할 수 밖에 없었던 이유",
    category: "Programming",
    speaker: "제온",
    image: "./resources/speaker/전규찬.png",
    belong: "카카오뱅크",
    introduce: "사용자, 메이커 모두를 아우르는 사람중심 개발자",
    detail: "모듈화를 할 수 밖에 없었던 이유에 대해 설명하고, 모듈화를 하게되면서 어떠한 고민들을 바탕으로 모듈화를 진행하는지 설명합니다.",
    track: "1",
    time: "11:00 ~ 11:20",
  },
  {
    title: "iOS 개발자를 위한 Unity",
    category: "Programming",
    speaker: "고야",
    image: "./resources/speaker/goya.png",
    belong: "(주)모카포트 대표, Unity certified instructor",
    introduce: "",
    detail: "Apple의 AR/VR 콘텐츠 제작을 위한 Unity 소개",
    track: "1",
    time: "11:00 ~ 11:20",
  },
  {
    title: "Swift concurrency: Good to know",
    category: "Programming",
    speaker: "김윤재",
    image: "./resources/speaker/yoonjae.png",
    belong: "LINE PLUS",
    introduce: "성장하고 싶은 주니어 개발자입니다.",
    detail: "Swift concurrency를 사용할 때 성능적으로 어떤 주의점이 있을까요? 이에 대한 궁금증에서 시작된 조사 결과를 공유하고자 합니다.",
    track: "1",
    time: "11:00 ~ 11:20",
  },
  {
    title: "SwiftData 언박싱 대신해드립니다!",
    category: "Programming",
    speaker: "토브",
    image: "./resources/speaker/tobe.png",
    belong: "",
    introduce: "길이 없다면 만들고, 벽이 있다면 부수자는 마음으로 공부하고 있습니다.",
    detail: "새롭게 출시된 SwiftData의 구성을 살펴보고 기존 CoreData 와 장단점을 비교하여 소개하며 SwiftData로 마이그레이션 과정 중 겪었던 경험들을 공유합니다.",
    track: "1",
    time: "11:00 ~ 11:20",
  }
];
