export const SPEAKERS = [
  {
    // 맨앞에 더미데이터 입니다.
    title: "Speakers",
    sub1: "총 4개의 트랙에서 펼쳐질",
    sub2: "KWDC23의 다양한 세션을 확인해보세요.",
  },
  {
    title: "미국에서 바라본 애플 생태계(feat. WWDC23)",
    category: "Apple eco-system",
    speaker: "Snack ・ 남관식",
    image: "./resources/speaker/snack.png",
    belong: "Apple Developer Academy @ POSTECH",
    introduce: "보다 더 넓은 세상으로 나아가려 합니다.",
    detail: "WWDC23을 참가하기 위해 미국을 다녀오며 직접 보았던 애플 생태계에 대해 공유합니다.",
    track: "1",
    time: "11:00 ~ 11:20",
  },
  {
    title: "10년된 서비스의 디자인 시스템 적용기",
    category: "Design",
    speaker: "엽",
    image: "./resources/speaker/엽.png",
    belong: "네이버",
    introduce: "",
    detail: "글로벌 서비스는 디자인 시스템을 어떻게 만들까? 디자인시스템을 만들기 위해 개발자와 디자이너는 어떻게 소통했을까?",
    track: "1",
    time: "11:00 ~ 11:20",
  },
  {
    title: "iOS17 커뮤니케이션 도구의 변화",
    category: "Business",
    speaker: "Yong",
    image: "./resources/speaker/yong.png",
    belong: "Kakao",
    introduce: "어쩌다 기획자가 된 5년차 서비스 기획자 용이라고 합니다.",
    detail: "iOS17이후 변경된 커뮤니케이션 도구의 변화와 메신저 서비스가 준비해야할 것들",
    track: "1",
    time: "11:00 ~ 11:20",
  },
  {
    title: "현대차 그리고 셔클",
    category: "Sponsorship session",
    speaker: "김용덕",
    image: "./resources/speaker/hyundai.png",
    belong: "현대자동차",
    introduce: "",
    detail: "현대자동차에서는 자동차만 만드는 것이 아닌, 모빌리티 서비스도 함께 만들고 있습니다.",
    track: "1",
    time: "11:00 ~ 11:20",
  },
  {
    title: "제조업에서 SwiftUI + TCA로 앱 개발하기",
    category: "Sponsorship session",
    speaker: "강성규",
    image: "./resources/speaker/hyundai.png",
    belong: "현대자동차",
    introduce: "",
    detail: "곧 공개됩니다.",
    track: "1",
    time: "11:00 ~ 11:20",
  },
  {
    title: "생성형AI 기반의 에듀테크 플랫폼",
    category: "Sponsorship session",
    speaker: "TBA",
    image: "./resources/speaker/udemy.png",
    belong: "웅진 Udemy",
    introduce: "교육업계 최초의 클라우드 전환. 1위 AI 학습 플랫폼, 웅진스마트올.",
    detail: "웅진스마트올 iOS 서비스 개발 사례 생성형AI를 통한 도약. Udemy를 통한 리스킬링&업스킬링",
    track: "1",
    time: "11:00 ~ 11:20",
  },
  {
    title: "Deep dive to SwiftUI Animation",
    category: "Programming",
    speaker: "그린",
    image: "./resources/speaker/그린.png",
    belong: "한화생명",
    introduce: "불확실성에 도전하는 개발자",
    detail: "SwiftUI Animation에 대해 탐구",
    track: "1",
    time: "11:00 ~ 11:20",
  },
  {
    title: "Swift 언어 히스토리 탐방",
    category: "Programming",
    speaker: "라이노",
    image: "./resources/speaker/라이노.png",
    belong: "비바리퍼블리카",
    introduce: "코딩의 가능성을 탐구하는 것을 즐깁니다.",
    detail: "Swift 언어가 발전해온 내용들과 올해 추가된 내용들을 리뷰하면서 Swift의 미래에 대한 생각을 나눕니다.",
    track: "1",
    time: "11:00 ~ 11:20",
  },
  {
    title: "Push Notifications Console 여행하기",
    category: "Programming",
    speaker: "아렉스",
    image: "./resources/speaker/아렉스.png",
    belong: "식신(주)",
    introduce: "인생은 trip",
    detail: "새롭게 소개 된 Push Notifications Console을 소개하며, 앞으로 어떻게 활용할지에 대해 얘기하고 싶습니다.",
    track: "1",
    time: "11:00 ~ 11:20",
  },
  {
    title: "LiDAR 스캐너의 활용법: Point Cloud Data, Object Capture",
    category: "Programming",
    speaker: "Tony",
    image: "./resources/speaker/tony.png",
    belong: "",
    introduce: "",
    detail: "LiDAR 스캐너의 기본동작 원리를 알아보자",
    track: "1",
    time: "11:00 ~ 11:20",
  },
  {
    title: "좋은 앱은 무엇일까요? 접근성 지원을 위한 iOS 개발자의 첫걸음",
    category: "Programming",
    speaker: "루카스 ・ 허성진",
    image: "./resources/speaker/lucas.png",
    belong: "인포마이닝",
    introduce: "귀여움받는 유능한 개발자가 되기 위해 열심히 노력하고 있습니다.",
    detail: "애플의 접근성 지원에 대한 진정성과, 개발자가 접근성 지원을 하면 얻는 이점을 이야기해 봅니다.",
    track: "1",
    time: "11:00 ~ 11:20",
  },
  {
    title: "매크로 부수고 부서지기",
    category: "Programming",
    speaker: "naljin",
    image: "./resources/speaker/naljin.png",
    belong: "지마켓",
    introduce: "우당탕탕 좌충우돌 얼레벌레 iOS 대모험",
    detail: "매크로에 대한 정의, 도입이유, 디자인 철학, 작성 방법, 동작 원리 등을 전반적으로 살펴볼 예정입니다.",
    track: "1",
    time: "11:00 ~ 11:20",
  },
  {
    title: "매크로 부수고 부서지기",
    category: "Programming",
    speaker: "소들이",
    image: "./resources/speaker/소들이.png",
    belong: "아프리카TV",
    introduce: "기록을 좋아하는 개발자입니다.",
    detail: "매크로에 대한 정의, 도입이유, 디자인 철학, 작성 방법, 동작 원리 등을 전반적으로 살펴볼 예정입니다.",
    track: "1",
    time: "11:00 ~ 11:20",
  },
  {
    title: "글로벌 앱 개발을 위한 Localization",
    category: "Programming",
    speaker: "애플사이다",
    image: "./resources/speaker/apple-sider.png",
    belong: "백패커(아이디어스)",
    introduce: "지속 가능한 성장을 지향합니다",
    detail: "새로운 Localization 기능을 알아보고, 글로벌 앱 예시를 통해 기술적 고민과 해결 방법을 소개합니다.",
    track: "1",
    time: "11:00 ~ 11:20",
  },
  {
    title: "우리가 모듈화를 할 수 밖에 없었던 이유",
    category: "Programming",
    speaker: "제온",
    image: "./resources/speaker/전규찬.png",
    belong: "카카오뱅크",
    introduce: "사용자, 메이커 모두를 아우르는 사람중심 개발자",
    detail: "모듈화를 할 수 밖에 없었던 이유에 대해 설명하고, 모듈화를 하게되면서 어떠한 고민들을 바탕으로 모듈화를 진행하는지 설명합니다.",
    track: "1",
    time: "11:00 ~ 11:20",
  },
  {
    title: "기대해주세요!",
    speaker: "2차 공개는 6월 30일로 예정되어 있습니다.",
    image: "./resources/speaker/empty.png",
    belong: "",
    introduce: "",
    detail: "",
    track: "1",
    time: "11:00 ~ 11:20",
  },
];
