export const SPEAKERS = [
  {
    // 맨앞에 더미데이터 입니다.
    title: "Speakers",
    sub1: "총 3개의 트랙에서 펼쳐질",
    sub2: "KWDC의 다양한 세션을 확인해보세요.",
  },
  {
    title: "세션 타이틀",
    speaker: "연사자",
    belong: "소속",
    detail: "세션에 대한 상세 설명이 들어가는 영역입니다.",
    track: "1",
    time: "11:00 ~ 11:20",
  },
  {
    title: "세션 타이틀",
    speaker: "연사자",
    belong: "소속",
    detail: "세션에 대한 상세 설명이 들어가는 영역입니다.",
    track: "1",
    time: "11:00 ~ 11:20",
  },
  {
    title: "세션 타이틀",
    speaker: "연사자",
    belong: "소속",
    detail: "세션에 대한 상세 설명이 들어가는 영역입니다.",
    track: "1",
    time: "11:00 ~ 11:20",
  },
  {
    title: "세션 타이틀",
    speaker: "연사자",
    belong: "소속",
    detail: "세션에 대한 상세 설명이 들어가는 영역입니다.",
    track: "1",
    time: "11:00 ~ 11:20",
  },
  {
    title: "세션 타이틀",
    speaker: "연사자",
    belong: "소속",
    detail: "세션에 대한 상세 설명이 들어가는 영역입니다.",
    track: "1",
    time: "11:00 ~ 11:20",
  },
  {
    title: "세션 타이틀",
    speaker: "연사자",
    belong: "소속",
    detail: "세션에 대한 상세 설명이 들어가는 영역입니다.",
    track: "1",
    time: "11:00 ~ 11:20",
  },
  {
    title: "세션 타이틀",
    speaker: "연사자",
    belong: "소속",
    detail: "세션에 대한 상세 설명이 들어가는 영역입니다.",
    track: "1",
    time: "11:00 ~ 11:20",
  },
  {
    title: "세션 타이틀",
    speaker: "연사자",
    belong: "소속",
    detail: "세션에 대한 상세 설명이 들어가는 영역입니다.",
    track: "1",
    time: "11:00 ~ 11:20",
  },
  {
    title: "세션 타이틀",
    speaker: "연사자",
    belong: "소속",
    detail: "세션에 대한 상세 설명이 들어가는 영역입니다.",
    track: "1",
    time: "11:00 ~ 11:20",
  },
  {
    title: "세션 타이틀",
    speaker: "연사자",
    belong: "소속",
    detail: "세션에 대한 상세 설명이 들어가는 영역입니다.",
    track: "1",
    time: "11:00 ~ 11:20",
  },
  {
    title: "세션 타이틀",
    speaker: "연사자",
    belong: "소속",
    detail: "세션에 대한 상세 설명이 들어가는 영역입니다.",
    track: "1",
    time: "11:00 ~ 11:20",
  },
  {
    title: "세션 타이틀",
    speaker: "연사자",
    belong: "소속",
    detail: "세션에 대한 상세 설명이 들어가는 영역입니다.",
    track: "1",
    time: "11:00 ~ 11:20",
  },
  {
    title: "세션 타이틀",
    speaker: "연사자",
    belong: "소속",
    detail: "세션에 대한 상세 설명이 들어가는 영역입니다.",
    track: "1",
    time: "11:00 ~ 11:20",
  },
  {
    title: "세션 타이틀",
    speaker: "연사자",
    belong: "소속",
    detail: "세션에 대한 상세 설명이 들어가는 영역입니다.",
    track: "1",
    time: "11:00 ~ 11:20",
  },
];
